---
all:
  children:
    prod:
      hosts:
        127.0.0.1: # Due to the way this template is configured, DO NOT CHANGE THIS!
      vars:
        connection: local
    automationcontroller:
      hosts:
        AAC01:
          ansible_host: 10.236.72.94

    automationhub:
      hosts:
        HERE: # FQDN of Automation Hub host(s). Can be commented out if not in use.

    automationedacontroller:
      hosts:
        HERE: # FQDN of Automation EDA Controller host(s)

    builder:
      hosts:
        HERE: # FQDN of builder host if you have one. Otherwise, can be Automation Hub host or commented out if not in use.

    # Only needed if installing AAP with automation, can be removed if you are not. See Install docs if unsure what server should be the database host.
    database:
      hosts:
        HERE:
  vars:
    env: prod
