---
controller_projects:
  - name: arista-veos-configuration
    description: Base Configs for Arista devices used for Ansiblefest 2024
    organization: Default
    scm_branch: main
    scm_clean: true
    scm_delete_on_update: false
    scm_type: git
    scm_update_on_launch: true
    scm_update_cache_timeout: 0
    scm_url: https://github.com/boblongmore/arista_configuration
    scm_credential: ansiblefest_2024_github
    allow_override: true
    default_environment: arista_netbox_v1

  - name: wwt-bigpanda-eda-demo
    description: project used for bigpanda and eda demo
    organization: Application-Demo
    scm_branch: main
    scm_clean: true
    scm_delete_on_update: false
    scm_type: git
    scm_update_on_launch: true
    scm_update_cache_timeout: 0
    scm_url: https://github.com/nsthompson/deploy-wwt-demo-app
    scm_credential: ansiblefest_2024_github
    allow_override: true
    default_environment: k8s-ee

  - name: arista-network-tests
    description: tests for use in ansiblefest2024 presentation
    organization: Default
    scm_branch: main
    scm_clean: true
    scm_delete_on_update: false
    scm_type: git
    scm_update_on_launch: true
    scm_update_cache_timeout: 0
    scm_url: https://github.com/boblongmore/arista_network_tests
    scm_credential: ansiblefest_2024_github
    allow_override: true
    default_environment: arista_netbox_v1

  - name: ansiblefest2024
    description: Main project for ansiblefest2024 presentation
    organization: Default
    scm_branch: main
    scm_clean: true
    scm_delete_on_update: false
    scm_type: git
    scm_update_on_launch: true
    scm_update_cache_timeout: 0
    scm_url: https://github.com/boblongmore/ansiblefest2024
    scm_credential: ansiblefest_2024_github
    allow_override: true
    default_environment: arista_netbox_v1
