---
controller_execution_environments:
  - name: k8s-ee
    image: 192.168.2.28/k8s-ee
    credential: automationhub

  - name: arista_netbox_v2
    image: 192.168.2.28/arista_netbox_v2
    credential: automationhub

  - name: arista_netbox_v3
    image: 192.168.2.28/arista_netbox_v3
    credential: automationhub

  - name: arista_netbox_v4
    image: 192.168.2.28/arista_netbox_v4
    credential: automationhub

  - name: arista_netbox_v5
    image: 192.168.2.28/arista_netbox_v5
    credential: automationhub
