---
controller_credential_types:
- name: NETBOX API Credential
  description: Netbox API Credential
  inputs:
    fields:
      - id: NETBOX_API
        type: string
        label: NetBox Host URL
      - id: NETBOX_TOKEN
        type: string
        label: NetBox API Token
        secret: true
    required:
      - NETBOX_API
      - NETBOX_TOKEN
  injectors:
    env:
      NETBOX_API: '{ { NETBOX_API }}'
      NETBOX_TOKEN: '{ { NETBOX_TOKEN }}'