---
controller_credentials:
  - name: Netbox-api-credentials
    description: Credentials for netbox
    organization: Default
    credential_type: NETBOX-API
    inputs:
      NETBOX_API: "{{ nb_url }}"
      NETBOX_TOKEN: "{{ nb_token }}"
  - name: Arista-veos-credential
    description: Credentials for Arista veos switches
    organization: Default
    credential_type: Machine
    inputs:
      username: "{{ veos_un }}"
      password: "{{ veos_pw }}"
      become_method: enable
  - name: Arista-netbox-vault
    description: credentials for netbox graphql queries
    organization: Default
    credential_type: Vault
    inputs:
      vault_password: "{{ vault_pw }}"
  - name: linux-server-creds
    description: credentials for linux servers in eveng
    organization: Default
    credential_type: Machine
    inputs:
      username: "{{ linux_un }}"
      password: "{{ linux_pw }}"
