---
controller_credentials:
- name: Netbox-api-credentials
  description: Credentials for netbox
  organization: Default
  credential_type: NETBOX API Credential
  inputs:
    username: "{{ nb_url }}"
    password: "{{ nb_token }}"