---
controller_credentials:
- name: Netbox-api-credentials
  description: Credentials for netbox
  organization: Default
  credential_type: NETBOX-API
  inputs:
    NETBOX_API: "{{ nb_url }}"
    NETBOX_TOKEN: "{{ nb_token }}"