---
controller_templates:
  - name: Arista-Base-Settings
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v1
    project: arista-veos-configuration
    playbook: playbooks/arista_base_settings.yml
    credentials:
      - Arista-veos-credential
    extra_vars:
      ansible_become: true
  - name: Arista-intf-settings
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v1
    project: arista-veos-configuration
    playbook: playbooks/arista_intf_config.yml
    credentials:
      - Arista-veos-credential
    extra_vars:
      ansible_become: true
  - name: Arista-bgp-settings
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v1
    project: arista-veos-configuration
    playbook: playbooks/arista_bgp_config.yml
    credentials:
      - Arista-veos-credential
      - Arista-netbox-vault
    extra_vars:
      ansible_become: true
  - name: linux-eveng-arista-config
    job_type: run
    inventory: ubuntu-servers-gns3-for-arista
    execution_environment: arista_netbox_v1
    project: arista-veos-configuration
    playbook: playbooks/linux_config.yml
    credentials:
      - linux-server-creds

  - name: Restart Demo App
    job_type: run
    inventory: wwt-bigpanda-eda-demo-inventory
    execution_environment: k8s-ee
    project: wwt-bigpanda-eda-demo
    playbook: restart_app_k8s.yml
    ask_variables_on_launch: true

  - name: Arista-upgrade-tests
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v4
    project: arista-network-tests
    playbook: playbooks/arista_tests.yml
    credentials:
      - Arista-veos-credential
    extra_vars:
      ansible_become: true

  - name: Arista-http-tests
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v4
    project: arista-network-tests
    playbook: playbooks/http_test.yml
    credentials:
      - linux-server-creds
      - Arista-netbox-vault
    ask_variables_on_launch: true
    extra_vars:
      ANSIBLE_HOST_KEY_CHECKING: false

  - name: Send message to Kafka
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v4
    project: ansiblefest2024
    playbook: playbooks/pb_kafka_prod.yml

  - name: Arista-test-interfaces
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v4
    project: arista-network-tests
    playbook: playbooks/arista_test_interfaces.yml
    credentials:
      - Arista-netbox-vault
      - Arista-veos-credential
    ask_variables_on_launch: true
    extra_vars:
      ansible_become: true

  - name: Arista-test-routing
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v4
    project: arista-network-tests
    playbook: playbooks/arista_test_routing.yml
    credentials:
      - Arista-netbox-vault
      - Arista-veos-credential
    ask_variables_on_launch: true
    extra_vars:
      ansible_become: true

  - name: arista-initiate-swim
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v4
    project: ansiblefest2024
    playbook: playbooks/arista_initiate_swim.yml
    credentials:
      - Arista-netbox-vault
      - Arista-veos-credential
    ask_variables_on_launch: true
    extra_vars:
      ansible_become: true

  - name: arista-update-netbox-sw
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v4
    project: ansiblefest2024
    playbook: playbooks/pb_update_nb_sw.yml
    credentials:
      - Arista-netbox-vault
      - Arista-veos-credential
    ask_variables_on_launch: true
    extra_vars:
      ansible_become: true

  - name: Arista-upgrade-device
    job_type: run
    inventory: arista-config-inv-from-netbox
    execution_environment: arista_netbox_v4
    project: ansiblefest2024
    playbook: playbooks/upgrade_arista_device.yml
    credentials:
      - Arista-netbox-vault
      - Arista-veos-credential
    ask_variables_on_launch: true
    extra_vars:
      ansible_become: true
