---
controller_templates:
- name: Arista-Base-Settings
  job_type: run
  inventory: arista-config-inv-from-netbox
  execution_environment: arista_netbox_v1
  project: arista-veos-configuration
  playbook: playbooks/arista_base_settings.yml
  credentials:
  - Arista-veos-credential
  extra_vars: 
    ansible_become: true
